# Site title and subtitle. This is used in _includes/header.html
title: 'Documentation'
subtitle: 'ATS Garage'

# if you wish to integrate disqus on pages set your shortname here
disqus_shortname: ''

# if you use google analytics, add your tracking id here
google_analytics_id: 'UA-69301419-1'

# Enable/show navigation. There are there options:
#   0 - always hide
#   1 - always show
#   2 - show only if posts are present
navigation: 2

# URL to source code, used in _includes/footer.html
codeurl: 'https://app.atsgarage.com/'

# Default categories (in order) to appear in the navigation
sections: [
    ['start', 'Getting Started'],
    ['bas', 'Basics'],
    ['feat', 'Features'],
    ['new', 'News'],
    ['ref', 'Reference'],
    ['ostree', 'OSTree']
    #['post', 'Posts']
]

# Links that should appear as top-bar navigation items
header-links: [
    ['Test 1', 'http://example.com'],
    ['Test 2', 'http://example.com/2']
]

# Keep as an empty string if served up at the root. If served up at a specific
# path (e.g. on GitHub pages) leave off the trailing slash, e.g. /my-project
baseurl: '' 

# Dates are not included in permalinks
permalink: none

# Syntax highlighting
highlighter: pygments

# Since these are pages, it doesn't really matter
future: true

# Exclude non-site files
exclude: ['bin', 'README.md','README.adoc','Gemfile*','Makefile','Dockerfile','publish_docs.sh','design']

gems: 
  - jekyll-asciidoc

asciidoctor:
  attributes:
    - hardbreaks!
    - source-highlighter=pygments
    - pygments-css=style


