# Site variant. Should be either 'here' or 'ats'
variant: here

# Site title and subtitle. This is used in _includes/header.html
title: 'Documentation'
subtitle: 'HERE OTA Connect SaaS'

# if you wish to integrate disqus on pages set your shortname here
disqus_shortname: ''

# if you use google analytics, add your tracking id here
google_analytics_id: ''

# Enable/show navigation. There are there options:
#   0 - always hide
#   1 - always show
#   2 - show only if posts are present
navigation: 2

# URL to source code, used in _includes/footer.html
codeurl: 'https://app.atsgarage.com/'

# Categories that can appear in the navigation
sections:
  - id: quickstarts
    title: Getting Started
  - id: manual
    title: Manual Setup Guides
  - id: concepts
    title: Concepts
  - id: faq
    title: Questions
  - id: tips
    title: Tips and Tricks
  - id: usage
    title: Using OTA Connect
  - id: prod
    title: Moving to Production
  - id: client-config
    title: Client Configuration


# This creates navigation tabs. 'title' is the display name of the tab, 'tab_id'
# is the id of the tab's div, and 'topics' is the list of sections (by id) that 
# should appear in the tab.
# 
# Note that any sections which aren't assigned to any navigation tab will not show 
# up in navigation anywhere
navigation_tabs:
  - title: Guides
    tab_id: guides
    topics:
      - quickstarts
      - prod
      - tips
      - usage
  - title: Reference
    tab_id: reference
    topics:
      - concepts
      - client-config
      - faq


# Legacy config option. Shouldn't be used anymore.
baseurl: '' 

# Dates are not included in permalinks
permalink: none

# Syntax highlighting
highlighter: rouge

# Since these are pages, it doesn't really matter
future: true

# Exclude non-site files
exclude: 
  - 'bin'
  - 'README.md'
  - 'README.adoc'
  - 'Gemfile*'
  - 'Makefile'
  - 'Dockerfile'
  - 'publish-docs.sh'
  - 'design'
  - '*.env'
  - '*.example'
  - '_secret*'
  - '_site-ats'
  - '_site-here'
  - '_tmp-git'

plugins: 
  - jekyll-asciidoc
  - octopress-debugger
  - asciidoctor-github-include
  - jekyll-compass

asciidoctor:
  attributes:
    product-name: HERE OTA Connect
    product-name-short: OTA Connect
    app-url: https://connect.ota.here.com
    source-highlighter: rouge

