= ATS Garage Docsite
:icons: font

This is the source for docs.atsgarage.com and for the HERE Developer Portal docs for HERE OTA Connect. It's built with Jekyll, a static site generator.

The text is written in Asciidoc, and rendered by link:http://asciidoctor.org[Asciidoctor]. Asciidoctor exercises a large number of styles, and has a tool to build stylesheets called asciidoctor-stylesheet-factory. ats.css is built with that tool; if you need to edit anything in there, do it via a pull request link:https://github.com/advancedtelematic/asciidoctor-stylesheet-factory[on our fork of asciidoctor-stylesheet-factory]. Any CSS changes that are specific to the ATS Garage docsite should be done in main.scss, though.

== Configuration

Building the site requires a github access token with access to ATS private repos. Pushing the site to docs.atsgargae.com requires a set of AWS IAM credentials with access to the `docs.atsgarage.com` S3 bucket. Pushing to the dev portal requires push access to link:https://gerrit.it.here.com/#/admin/projects/DOCS/ota_update_platform[].

=== Github token

. https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line[Generate the token.]
. Copy `_secrets.yml.example` to `_secrets.yml`, substituting your token.

=== AWS credentials

. Get the `docs` IAM credentials from the Infra team.
. copy `s3_credentials.env.example` to `s3_credentials.env`, substituting the real credentials.

== Build

There are two different config files, one for the ATS build, and one for the HERE build.

Build the site with link:docker.com[Docker]:

    ./build-ats.sh

OR

    ./build-here.sh


Build the site from a local jekyll install:

   bundle install
   jekyll build --config _conf-<ats|here>.yml,_secrets.yml




== Publish

    ./publish-ats.sh

OR

    ./publish-here.sh

== Debugging

If you're having issues with how jekyll is rendering the site, you can add debug breakpoints to any of the layouts or includes with a {% debug %} liquid tag. See the debugger docs at https://github.com/octopress/debugger.

If it's a problem that only affects a single page, you can set the layout of that page to 'debug'.

== Navigation

The sidebar navigation can be customized in `_conf-<ats|here>.yml`. The `sections` key lists the sections that will appear in the navigation, and the `navigation_tabs` key lists the tabs, and which sections each one contains. (Details in the yaml comments.)

== Multiple-language code tabs/code samples

You can make codetabs appear by using asciidoc attributes. Just put multiple `source` blocks, give one of them the "primary" role, and the others "secondary". Make sure to give each block a name; that's what will be used for the title of the tab. Example:

....
[source,C,role="primary"]
.C (ANSI)
----
/* Hello World in C, Ansi-style */

#include <stdio.h>
#include <stdlib.h>

int main(void)
{
  puts("Hello World!");
  return EXIT_SUCCESS;
}
----

[source,python,role="secondary"]
.Python
----
print("Hello World")
----

[source,python,role="secondary"]
.link:https://esolangs.org/wiki/Ook![Ook]
----
Ook. Ook? Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook.
Ook. Ook. Ook. Ook. Ook! Ook? Ook? Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook.
Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook? Ook! Ook! Ook? Ook! Ook? Ook.
Ook! Ook. Ook. Ook? Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook.
Ook. Ook. Ook! Ook? Ook? Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook?
Ook! Ook! Ook? Ook! Ook? Ook. Ook. Ook. Ook! Ook. Ook. Ook. Ook. Ook. Ook. Ook.
Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook! Ook. Ook! Ook. Ook. Ook. Ook. Ook.
Ook. Ook. Ook! Ook. Ook. Ook? Ook. Ook? Ook. Ook? Ook. Ook. Ook. Ook. Ook. Ook.
Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook! Ook? Ook? Ook. Ook. Ook.
Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook? Ook! Ook! Ook? Ook! Ook? Ook. Ook! Ook.
Ook. Ook? Ook. Ook? Ook. Ook? Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook.
Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook! Ook? Ook? Ook. Ook. Ook.
Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook.
Ook. Ook? Ook! Ook! Ook? Ook! Ook? Ook. Ook! Ook! Ook! Ook! Ook! Ook! Ook! Ook.
Ook? Ook. Ook? Ook. Ook? Ook. Ook? Ook. Ook! Ook. Ook. Ook. Ook. Ook. Ook. Ook.
Ook! Ook. Ook! Ook! Ook! Ook! Ook! Ook! Ook! Ook! Ook! Ook! Ook! Ook! Ook! Ook.
Ook! Ook! Ook! Ook! Ook! Ook! Ook! Ook! Ook! Ook! Ook! Ook! Ook! Ook! Ook! Ook!
Ook! Ook. Ook. Ook? Ook. Ook? Ook. Ook. Ook! Ook. Ook! Ook? Ook! Ook! Ook? Ook!
Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook.
Ook. Ook. Ook. Ook. Ook! Ook.
----
....
