---
layout: page
title: "Introduction"
category: hidden
order: 1
date: 2016-11-28 15:42:34
---

== What is OSTree?

Short answer? It's git, but for complete, bootable filesystem images.

OSTree checksums individual files, and then stores them in a content-addressed-object store. When you "check out" a filesystem tree, the files get hardlinked into a normal filesystem layout. This has some fantastic advantages for embedded systems:

* Atomic updates and rollbacks
* Incremental updates at the file level
* Parallel installation of 2 or more completely different roots
* Complete binary history

== What is TreeHub?

If OSTree is 'git for filesystems', TreeHub is 'GitHub for OSTree'. TreeHub is integrated into ATS Garage, so as soon as you push your latest build up to TreeHub, you can immediately create campaigns to get it sent out to your fleet of devices.

== What are the system prerequisites? What hardware is supported?

ATS provides layers for integrating OSTree into your Yocto/OpenEmbedded project. Fundamentally, there are two layers that are needed. The `meta-updater` layer is cross-platform, and provides the OSTree management tools.

We also provide board support layers, because OSTree requires integration into the bootloader. Right now we have board support for the following devices/architectures:

* link:https://github.com/advancedtelematic/meta-updater-raspberrypi[Raspberry Pi 3 rev. 2]
* link:https://github.com/advancedtelematic/meta-updater-minnowboard[Minnowboard Max/Turbot]
* link:https://github.com/advancedtelematic/meta-updater-qemux86-64[Native QEMU emulation]

We're working on expanding board support, but if you're familiar with your board's internals you can probably get it running yourself. We've posted a walkthrough of how we got the R-Pi running, and you can find detailed technical documentation on developing board support layers link:example.com[here].



// prerequisites

// - Yocto version: krogoth
// - poky

// * download the meta-updater layer
// * download the BSP layer

// what do i need to know?

// - adding to the bitbake process to push to the OSTree repo
// - how OSTree works, in depth (read the OSTree docs)

//   - /var is special:
//     - initially empty, things you put there persist through full filesystem updates


//   - /usr
//     -

//   - /etc
//     - funky 3-way merge behaviour

// BSP support is all about tuning uboot to work with OSTree

// - add configuration to your uboot to:
//   - read the config from uEnv.txt
//   - load the specified kernel
//   - checking which deployment (i.e., which OSTree commit) to boot

