---
layout: page
title: "Client configuration options"
category: ref
date: 2016-12-21 17:02:37
---
:icons: font

== Starting the SOTA client

In general, the SOTA client should be run at startup, as a service. For example, if you're using systemd you would want a service file like this:

.Example: systemd service file
----
[Unit]
Description=ATS Garage Client
Wants=network-online.target
After=network.target network-online.target
Requires=network-online.target

[Service]
RestartSec=5
Restart=on-failure
Environment="RUST_LOG=info"
DefaultTimeoutStopSec=5
ExecStart=/usr/bin/sota_client --config /etc/sota.toml

[Install]
WantedBy=multi-user.target
----

Systemd is not a requirement, of course; you can use whatever startup system you like, or just run directly from the command line to test.

== SOTA Client config file guide

The config file for the SOTA client is in TOML format, and can be invoked at startup with `sota_client  --config /path/to/config_file.toml`. You can download the config file for your particular device from the device page, or if you installed from a deb or rpm package, the config file for your device was included in that package.

=== [auth]

This section is required for connection to ATS Garage. It should never need to be changed.

----
[auth]
server = "https://auth-plus.gw.prod01.advancedtelematic.com"
client_id = "bf66425f-d4d6-422b-b510-7c7f178af9fe"
client_secret = "hr8nEWzQc9"
credentials_file = "/opt/sota/credentials.toml"
----

=== [core]

This section contains configuration for communicating with the vehicle endpoints in ATS Garage.

----
[core]
server = "https://sota-core.gw.prod01.advancedtelematic.com"
polling = true <1>
polling_sec = 10 <2>
----
<1> Boolean indicating whether ATS Garage should be polled for new updates. In general, you would want to leave this on, but if you have another service that's triggering update checks using the link:../cli/client-commands-and-events-reference.html#commands[GetUpdateRequests command], you might want to disable update polling.
<2> The polling frequency in seconds.

=== [device]

This section contains device-specific configuration.

----
[device]
uuid = "123e4567-e89b-12d3-a456-426655440000" <1>
system_info = "system_info.sh" <2>
packages_dir = "/tmp/" <3>
package_manager = "off" <4>
certificates_path = "/tmp/sota_certificates" <5>
----
<1> The UUID of the device. This is provided in the config file you can download from the device page, and shouldn't be changed.
<2> The script to use to gather system information. By default, this uses link:https://github.com/advancedtelematic/rvi_sota_client/blob/master/run/system_info.sh[system_info.sh].
<3> The location SOTA Client should use for temporary package storage until they are processed by the software loading manager.
<4> The software loading manager backend to use. Possible values are `deb`, `rpm`, `ostree`, and `off`. If an external software loading manager is in use, this should be set to `off`.
<5> The certificate authorities the ATS Garage Client trusts.

=== [network]

This section contains network configuration information. Some values may be ignored if the corresponding communication methods aren't enabled.

----
[network]
http_server = "127.0.0.1:8888" <1>
socket_commands_path = "/tmp/sota-commands.socket" <2>
socket_events_path = "/tmp/sota-events.socket" <3>
websocket_server = "127.0.0.1:9081" <4>
rvi_edge_server = "127.0.0.1:9080" <5>
----
<1> The host and port the client should listen on for commands if the http gateway is enabled in the [gateway] section.
<2> The name of the unix domain socket to be used for receiving commands, if the socket gateway is enabled in the [gateway] section.
<3> The name of the unix domain socket to be used for sending events, if the socket gateway is enabled in the [gateway] section.
<4> The host and port to listen for local websocket connections on. Could be used, for example, for integration with an HTML5 HMI.
<5> Legacy support for RVI communication; ATS Garage does not use RVI.

=== [gateway]

The SOTA Client communicates with the device's software loading manager (or other interested parties) through various gateways. For more details on how this works, please see the link:../cli/client-commands-and-events-reference.html[Client commands and events API reference].

----
[gateway]
console = false <1>
dbus = false
http = false <2>
rvi = false
socket = false <3>
websocket = true
----
<1> REPL mode, generally only enabled for debugging.
<2> Simple http server, for sending commands to the client remotely. Note that this does _not_ affect how the client communicates with the server.
<3> Unix domain sockets for local communication.

==== Optional gateway: [dbus]

This section contains values for dbus configuration. If you enable the `dbus` gateway, you'll need to populate this section. Note that having this section defined does _not_ imply that dbus will necessarily be used; if the dbus gateway is turned off in the `[gateway]` section, any values configured here are ignored.

----
[dbus]
name = "org.ats.GarageClient"
path = "/org/ats/GarageClient"
interface = "org.ats.GarageClient"
software_manager = "org.genivi.SoftwareLoadingManager"
software_manager_path = "/org/genivi/SoftwareLoadingManager"
timeout = 60
----
