= Troubleshooting
:page-layout: page
:page-categories: [tips]
:page-date: 2017-06-13 10:51:53
:page-order: 99
:icons: font
:toc: macro

toc::[]

== Build problems

=== GnuTLS build fails with older kernels

GnuTLS currently requires a kernel >= 3.17 to build. If you're using an older kernel, you'll see an error like this:

----
../../../gnutls-3.5.3/lib/nettle/rnd-linux.c: In function 'have_getrandom':
../../../gnutls-3.5.3/lib/nettle/rnd-linux.c:59:42: error: 'SYS_getrandom' undeclared (first use in this function)
 #  define getrandom(dst,s,flags) syscall(SYS_getrandom, (void*)dst, (size_t)s, (unsigned int)flags)
----

This is an upstream problem; until it's fixed in upstream poky, you can link:../files/gnutls-fix.patch[download this patch] to your `poky` directory and apply it to fix the issue.

=== Build didn't work after switching architectures

You might have tried something like this:

----
source meta-updater/scripts/envsetup.sh raspberrypi3

{ build an image ... }

cd ..
source meta-updater/scripts/envsetup.sh qemux86-64

----

*This doesn't work.* The setup script sets up certain environment variables for bitbake, but it also generates your `local.conf` and `bblayers.conf` files. If it finds existing files, however, it leaves them alone, and only sets up the environment. If you want to switch architectures, you also need to change your config files. You can do that by deleting/renaming your old ones and re-generating the config files. Don't forget to add your credentials and other customizations to the re-generated files!

Depending on your use case, however, it often makes more sense to just keep separate project directories for your separate architectures, and share the state cache and downloads directories between them.

== Runtime problems

=== File ownership incorrect after an update (static UID to name mapping)

Yocto assigns numeric user IDs (UIDs) to Linux login names at system build time. This dynamic assignment does not always work correctly for an embedded system that is receiving software updates, because the numeric UID of a service can change between builds, but any files the service created on the file system will remain owned by the original UID.

The solution is to manually set the contents of `/etc/passwd` and `/etc/group` for your system, so that the UIDs remain stable between builds.

This is required if you have a service that does all of the following:

* Creates files
* Runs as an account that is not one of the 'standard' accounts (`root`, `floppy`, `man`, `tape`, etc)
* The recipe for the service creates the user (using `useradd`)

In this case, you should set link:http://www.yoctoproject.org/docs/2.4.1/mega-manual/mega-manual.html#var-USERADDEXTENSION[USERADDEXTENSION] to `"useradd-staticids"`. The link:http://www.yoctoproject.org/docs/2.4.1/mega-manual/mega-manual.html#ref-classes-useradd[useradd] section of the Yocto Mega Manual describes this process in more detail.


.Don't see your problem here?
****
We'd love to hear from you about how we can improve the docs and make ATS Garage better. Contact link:mailto:support@atsgarage.com[support@atsgarage.com] and we'll do our best to help.
****
