:page-layout: page
:page-title: "Install and configure the ATS Garage client"
:page-category: start-manual
:page-order: 1
:page-date: 2017-01-16 18:09:07
:icons: font
:toc: macro

If you are planning to use a custom software installer with ATS Garage, or if you want to install from packages but you don't use systemd, you'll need to complete some manual steps that are taken care of automatically in the OSTree or package-based getting started guides. You'll need to:

. Acquire a client binary that runs on your system
. Add the client to your init system
. Configure the client to your needs

We'll go into a bit more detail on each step here. Since many manual configuration setups will need to support SoCs/architectures that we don't supply pre-built binaries for, we'll include instructions on building the client, using a Raspberry Pi as an example.

toc::[]

== Build a binary

The ATS Garage client is completely open source; you can build it yourself on more or less any platform that runs Linux and the Rust compiler. At the moment, the only pre-built binaries we're offering are for 64 bit Linux, so if you're on another architecture you'll need to build it yourself.

That's not a difficult process, though: just link:https://github.com/advancedtelematic/rvi_sota_client[clone the repo from github] (stable branch recommended), install Rust if you haven't already, and build. Here's what that process looks like on a Raspberry Pi with a fresh Raspbian install:

.Example: Raspberry Pi 2
----
# Install the basic build tools and dev libraries needed
apt-get install -y autoconf git libdbus-1-dev libtool openssl libssl-dev lshw jq

# Install Rust
curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable -y
export PATH=/root/.cargo/bin:$PATH

# Download the client source code
git clone https://github.com/advancedtelematic/rvi_sota_client.git -b stable
cd rvi_sota_client

# Build
cargo build --release
----

Depending on your system, it may take quite some time to compile, as Cargo downloads and compiles all the necessary dependencies. On a Raspberry Pi 2, the `cargo build --release` step took about 30 minutes in total. The whole process, including installing packages and installing the Rust toolchain, took about 40 minutes.

== Add the client to your init system

The ATS Garage client needs to run as root, and should be run at startup. You can set that up however you like, but the best way is to add it to your platform's init system. In Raspbian, that means systemd.

First, we create a file at `/lib/systemd/system/sota.service`. We populate it as follows:

.Example: Raspbian systemd service file
----
[Unit]
Description=SOTA Client
Wants=network-online.target
After=network.target network-online.target
Requires=network-online.target

[Service]
RestartSec=5
Restart=on-failure
Environment="RUST_LOG=info"
DefaultTimeoutStopSec=5
ExecStart=/usr/bin/sota_client --config /etc/sota.toml

[Install]
WantedBy=multi-user.target
----

Then, to enable the service:

----
sudo systemctl daemon-reload
sudo systemctl enable sota.service
----

If you use a different init system, like Upstart or systemv, you should consult their documentation for detailed instructions.

== Configure the client to your needs

The ATS Garage client has a wealth of configuration options, but most of them should not be necessary to change. The config file you download from ATS Garage includes all the correct configuration information, server addresses, and so on. Complete documentation on all of the config options is available link:../cli-dev/client-configuration-guide.html[here].

There are three important config options that you should be aware of when manually installing the client, however: the package manager, the trusted certificate list, and the system info script.

=== Package manager selection

The ATS Garage client downloads update files from ATS Garage, then either installs them itself, or passes them off to an external installer. The option of which installer to use is found in the sota.toml config file.

When you download the config file on its own, you can select which package manager to use from a drop-down menu. If you select *dpkg*, *rpm*, or *OSTree*, the client will call the respective package manager. If it is set to *off*, the client will simply download the update files and publish an event through the command/event API. With this behaviour, the client will download a package, place it in a temp directory (also configurable in sota.toml), and emit an event notifying an external software loading manager that there has been a package downloaded.

To point it towards your preferred package manager instead, set `package_manager` in the `[device]` section to either `deb` or `rpm`.

If you want more information on how to use the ATS Garage client with an external software loading manager, you'll need the advanced documentation about link:../cli-dev/client-configuration-guide.html[configuration options] and link:../cli-dev/client-commandevent-api.html[the command/event API].

=== System info script

The ATS Garage client reports system information to ATS Garage, and needs a way to get that info. The default is a script called system_info.sh, which depends on `lshw`. This script can be found in the sota client repo, in the `run` directory. You can also implement a custom system info script; as long as it outputs a JSON object, ATS Garage will handle it. However, for our Raspberry Pi example, we will just use the default script, and place it in the place expected by default in the config file ATS Garage downloaded:

.Example: Raspberry Pi 2
----
cp run/system_info.sh /usr/bin/
----

=== Trusted certificate authorities

Because the ATS Garage client connects via HTTPS to ATS Garage (and Amazon S3), it needs a list of certificate authorities to trust. You can either edit the config file to point to your operating system's certificates file, or you can use the one bundled with the ATS Garage client. Again, for simplicity, we'll use the one provided in our example, and copy it to the default location.

.Example: Raspberry Pi 2
----
cp run/sota_certificates /etc/
----


