= Client command/event API
:page-layout: page
:page-categories: [cli-dev]
:page-date: 2017-01-16 21:09:08
:icons: font


The ATS Garage client (aktualizr) communicates with other processes on the host system over a command and event API. This API can function over D-Bus or via simple unix domain sockets.

The client receives *commands*, and broadcasts *events*. Any interested parties on the system can subscribe to events, and send commands to the client.

== Events

`Error(String)` -- General error event with a printable representation for debugging.

`Authenticated` -- Authentication with SOTA Core was successful.

`NotAuthenticated` -- An operation failed because we are not currently authenticated.

`UpdatesReceived(Vec<UpdateRequest>)` -- Client has received a notification from Core of pending or in-flight updates. It includes a vector of one or more update UUIDs received from Core.

`UpdateAvailable(UpdateAvailable)` -- Used only when using RVI: a notification from RVI of a pending update.

`NoUpdateRequests` -- The client has no more outstanding update requests.

`FoundInstalledPackages(Vec<Package>)` -- The following packages are installed on the device.

`FoundSystemInfo(String)` -- An update on the system information was received.

`DownloadingUpdate(UpdateRequestId)` -- Downloading an update.

`DownloadComplete(DownloadComplete)` -- An update was downloaded.

`DownloadFailed(UpdateRequestId, String)` -- Downloading an update failed.

`InstallingUpdate(UpdateRequestId)` -- Installing an update.

`InstallComplete(UpdateReport)` -- An update was installed.

`InstallFailed(UpdateReport)` -- The installation of an update failed.

`UpdateReportSent` -- An update report was sent to the Core server.

`InstalledPackagesSent` -- A list of installed packages was sent to the Core server.

`InstalledSoftwareSent` -- A list of installed software was sent to the Core server.

`SystemInfoSent` -- The system information was sent to the Core server.

`InstalledSoftwareNeeded` -- A broadcast event requesting an update on externally installed software.

`UptaneTimestampUpdated` -- A new signed nonce was received from the Uptane timestamp server

`UptaneTargetsUpdated` -- A new targets.json was received from the Uptane director

== Commands

`Authenticate(Option<ClientCredentials>)` -- Authenticate with the auth server.

`Shutdown` -- Shutdown the client immediately.

`GetUpdateRequests` -- Check for any pending or in-flight updates.

TIP: Assuming a polling interval is set, the client will periodically check for updates. If the polling interval is set to 0, this command can be sent to force the client to check for updates. This would be useful, for example, in a system with SMS shoulder-tap notifications.

`ListInstalledPackages` -- List the installed packages on the system.

`ListSystemInfo` -- List the system information.

TIP: This tells the client to invoke the command set for `system_info` in the client configuration file.

`StartDownload(UpdateRequestId)` -- Start downloading an update.

`AbortDownload(UpdateRequestId)` -- Abort the download of an update.

`StartInstall(UpdateRequestId)` -- Start installing an update.

TIP: This only applies if the package_manager is set to `deb` or `rpm` in the config file. If it's set to `off`, the software loading manager would start the install after it sees a DownloadComplete event.

`SendInstalledPackages(Vec<Package>)` -- Send a list of packages to the Core server.

TIP: SendInstalledPackages is intended to send a complete list of all packages on the device. Each time you send the command, the complete list of packages on Core will be *overwritten* with the info you send--not updated or appended.

`SendInstalledSoftware(InstalledSoftware)` -- Send a list of all packages and firmware to the Core server.

`SendSystemInfo` -- Send the system information to the Core server.

`SendUpdateReport(UpdateReport)` -- Send a package update report to the Core server.

== Gateways

If you are interested in implementing an external software installer using the command and event gateways, we would love to hear from you. link:mailto:support@atsgarage.com[Contact ATS Garage Support] and we'll do our best to support your efforts.

