= Client provisioning methods
:page-layout: page
:page-categories: [client-config]
:page-date: 2018-07-05 13:31:58
:page-order: 25
:icons: font

// TODO MERLIN: Explain the difference between different provisioning methods, why you might want to do one or another, and what steps you need to take for each.

In OTA Connect, the provisioning process ensures that the device has a certificate and a unique identifier. After a device has been provisioned, it can receive software updates. OTA Connect supports two types of provisioning:

* *Automatic provisioning*
+
Devices use temporary provisioning credentials to request permanent credentials from the server. You download the temporary provisioning credentials from the OTA Connect web app and install them on a device. Once the device registers with the server for the first time, the server assigns permanent credentials to the device. The device then uses these permanent credentials for all future transactions.

* *Implicit Provisioning*
+
Devices already have permanent credentials installed. The server doesn't issue any credentials to devices. Instead, you use a root CA certificate to sign the credentials that you install on the device. You then install the same root CA certificate on the OTA Connect server.
Every time the device attempts to connect, the server verifies that the device credentials are signed by the same CA that you originally installed on the server.

The type of provisioning that you choose depends on your requirements. If you're just testing and want to get started quickly, automatic provisioning is fine. It is easier to set up but is less secure. Because server self-signs the credentials that it issues to devices, the devices have no way of verifying the integrity of the server. This level of security is not suitable for a production environment. The device should always be able to verify that is communicating with a genuine OTA Connect server. Once you move to production, you should look at some form of implicit provisioning. The most common way to implicity provision devices is with a Hardware Security Module (HSM).

The following instructions describe how to set up both types of provisioning methods:

.To set up automatic provisioning, follow these steps:
. In the OTA Connect web app, navigate to the provisioning keys page and click *+Add key*:
+
Example URL: https://connect.ota.here.com/#/profile/access-keys
. In the dialog that appears, enter a description and an expiry date for your provisioning key.
. Click *Add key* to download a zip file that contains the provisioning key and credentials.
. Install Aktualizr on the device and place the zip file in a location that Aktualizr can access. 
. Edit the following `.toml` configuration file:
+
link:../config/sota_autoprov.toml[config/sota_autoprov.toml]
. Update the configuration file with the path to the zip file that you saved in the previous step and start Aktualizr on the device.
+
** When Aktualizr starts, it uses the provisioning key to register with the device gateway HTTPS API. 
** The server registers the new device and returns a PKCS#12 archive containing the real credentials for the device. This archive contains the root CA certificate and client certificate.
** The device unpacks the this archive into the paths that are specified in the `[storage]` section of the config.
//MC: ?? my [storage] just says "sqlite"...is that a path?
** The device uses this private key and certificate for all further communication with the server.

Aktualizr uses the following configuration options for automatic provisioning:

[options=header]
|===================
| Configuration option | Where comes from
| Server URL | Read from the credentials archive
| TLS key/cert/root CA | Read from the credentials archive
| Device ID | Automatically generated by Aktualizr
| Uptane public/private key | Automatically generated by Aktualizr
| Uptane primary serial number | Automatically generated by Aktualizr
| Primary ECU Hardware ID | Automatically generated by Aktualizr
|===================

.To set up implicit provisioning, follow these steps:


. Generate a root CA private key and self-signed certificate.
+
If you do not have your own CA certificate for signing device certificates, you can generate a self-signed certificate for testing.
+
First, create a directory structure for the keys, and grab sample configurations for the certificates from the OTA Community Edition project:
+
[source,bash]
----
export SERVER_NAME=myservername
export SERVER_DIR="./${SERVER_NAME}" DEVICES_DIR="./${SERVER_NAME}/devices" CWD="${PWD}"
mkdir -p "$DEVICES_DIR" certs
for file in client.cnf device_ca.cnf server.ext client.ext server.cnf server_ca.cnf; do
  curl -o certs/$file https://raw.githubusercontent.com/advancedtelematic/ota-community-edition/master/scripts/certs/$file
done
----
+
Then, generate the key and cert using openssl on the command line:
+
[source,bash]
----
include::https://raw.githubusercontent.com/advancedtelematic/ota-community-edition/master/scripts/start.sh[tags="genserverkeys"]
----
+
This will create a `./${SERVER_DIR}/devices/` directory with the `ca.crt` certificate and a `ca.key` private key. Keep the private key safe and secure.
. Upload the root CA certificate to the server. To add a root CA certificate to link:https://atsgarage.com[ATS Garage], contact link:mailto:support@atsgarage.com[support@atsgarage.com].
. Download a temporary credentials archive.
.. In the OTA Connect web app, navigate to the provisioning keys page and click *+Add key*:
+
Example URL: https://connect.ota.here.com/#/profile/access-keys
.. In the dialog that appears, enter a description and an expiry date for your provisioning key.
.. Click *Add key* to download a zip file that contains the provisioning key and credentials.
.. Place the zip file in a location that Aktualizr can access. 
. Add the following lines to your `conf/local.conf`:
+
----
SOTA_CLIENT_PROV = "aktualizr-implicit-prov"
SOTA_PACKED_CREDENTIALS = "/path/to/provisioning_credentials.zip"
----
+
Set `SOTA_PACKED_CREDENTIALS` to the path of the zip file that you downloaded in the previous step.
. Build a standard image using bitbake. Make sure an ssh server is installed; usually you can do this the following configuration:
// MC: Why do we say "usually"? Depending on what?
+
 `IMAGE_INSTALL_append = " dropbear "`.
+
When you build the image, the client downloads the server's internal root CA certificate. Currently, `implicit_writer` is used to read the server’s root CA from the archive file that you defined in the `SOTA_PACKED_CREDENTIALS` setting. The root certificate is then installed on the device during the build process.
// MC: Why "currently"? Why are we introducing "implicit writer" without any explanation?
. Boot the image.
. Generate a device certificate and key, and sign it with the root CA you just created.
+
Generate a UUID for the device, and make a directory for it:
+
[source,bash]
----
export DEVICE_UUID=$(uuidgen | tr "[:upper:]" "[:lower:]")
export device_id=${DEVICE_ID:-${DEVICE_UUID}} device_dir="${DEVICES_DIR}/${DEVICE_UUID}"
mkdir -p "${device_dir}"
----
+
Then, generate the device certificate and key using openssl:
+
[source,bash]
----
include::https://raw.githubusercontent.com/advancedtelematic/ota-community-edition/master/scripts/start.sh[tags="genclientkeys"]
----
. Install the generated device certificate on the client device.
// MC: How exactly? is the command similar to the one for HSM? Don't I need to reboot or something?
.. To authenticate the client device, the server verifies that the client's certificate is signed by your root CA private key. This is the root CA certificate that you uploaded to the server.
.. To authenticate the server, the client verifies that the server’s certificate is signed by the internal root CA private key. This is the internal root CA private key that was installed on the device during the build process. 
.. After authentication is complete, the device is provisioned, and appears online in the web UI.

Aktualizr uses the following configuration options for implicit provisioning:

[options=header]
|===================
| Configuration option         | Where it will come from/what it does
| Server URL                   | Read from credentials archive
| Server Root CA cert          | Read from credentials archive
// MC: Is the "internal root CA" that we talk about in the instructions?
| Fleet Root CA cert           | Chain of trust for a device fleet; provided by the user. Must be uploaded by user to the server.
// MC: Why is the term "Fleet Root CA cert" not used at all in the instructions
| Fleet Root CA private key    | Key for signing device certs in the fleet; provided by user, but used only for signing. Not stored on device.
// MC: Why is the term "Fleet Root CA cert" not used at all in the instructions? Is this is "offline key" we talk about in whitepapers?
| TLS device cert              | Pre-installed or manually installed; must be signed by Fleet Root CA private key
// MC: Why is the term "TLS device cert" not used at all in the instructions?  When Pre-installed and when manually installed? by who?
| TLS device key               | Pre-installed or manually installed
| Device ID                    | Read from Common Name field of TLS device cert
| Uptane public/private key    | Automatically generated by Aktualizr
| Uptane primary serial number | Automatically generated by Aktualizr
| Primary ECU Hardware ID      | Automatically generated by Aktualizr
|===================