= Key Concepts
:page-layout: page
:page-categories: [using-libaktualizr]
:page-date: 2018-11-28 14:19:35
:page-order: 3
:icons: font

See the comments in the asciidoc source.


////
      FYI: We already have conceptual information else where in the documentation
      (see: https://docs.atsgarage.com/concepts/understanding-the-ats-garage-client.html)

      This topic shouldn't redescribe all those concepts, but it should point to the most
      important concepts that you should familiarize yourself with before starting on
      production code with libaktualizr

      For example, you don't need to redescribe provisioning methods, but you say
      something like "provisioning is a thing you need to know about because blah..." and point
      the reader to the existing topic:
      
       ../client-config/client-provisioning-methods.html

      For inspiration: The OLP data vizualiation lib provides a very basic summary of the 
      key concepts and points to pages where you can find out more:
      https://developer.here.com/olp/documentation/data-visualization-library/dev_guide/pages/concepts.html

      If there are concepts that are specific to libaktualizr, you can add them here too, but try to 
      avoid overexplaning things with sections like "Why not IPC?" or "Why not a C API?".

      If you want, you can create a seprate FAQs page for these types of questions.


////
