= Generate and install root certificates
:page-layout: page
:page-categories: [prod]
:page-date: 2018-08-29 11:12:06
:page-order: 3
:icons: font

Before you can start provisioning with device credentials, you'll need the following components:

- A root CA certificate and private key
- Device credentials that are signed by root CA certificate
- The internal root CA certificate of your device gateway

The following instructions describe how you can generate these components. Getting a root CA certificate is beyond the scope of these instructions, but we can show you how to generate a self-signed certificate for testing.
// tag::install-root-ca[]

To generate and install root certificates, follow these steps: ::
. Generate a root CA private key and self-signed certificate.
+
If you do not have your own CA certificate for signing device certificates, you can generate a self-signed certificate for testing.
+
First, create a directory structure for the keys, and grab sample configurations for the certificates from the OTA Community Edition project:
+
[source,bash]
----
export SERVER_NAME=myservername
export SERVER_DIR="./${SERVER_NAME}" DEVICES_DIR="./${SERVER_NAME}/devices" CWD="${PWD}"
mkdir -p "$DEVICES_DIR" certs
for file in client.cnf device_ca.cnf server.ext client.ext server.cnf server_ca.cnf; do
  curl -o certs/$file https://raw.githubusercontent.com/advancedtelematic/ota-community-edition/master/scripts/certs/$file
done
----
+
Then, generate the key and cert using openssl on the command line:
+
[source,bash]
----
include::https://raw.githubusercontent.com/advancedtelematic/ota-community-edition/master/scripts/start.sh[tags="genserverkeys"]
----
+
This will create a `./${SERVER_DIR}/devices/` directory with the `ca.crt` certificate and a `ca.key` private key. Keep the private key safe and secure.
. Upload the root CA certificate to the server. To add a root CA certificate to link:https://connect.ota.here.com[HERE OTA Connect], contact link:mailto:otaconnect.support@here.com[otaconnect.support@here.com].
. Generate a device certificate and key, and sign it with the root CA you just created.
+
Generate a UUID for the device, and make a directory for it:
+
[source,bash]
----
export DEVICE_UUID=$(uuidgen | tr "[:upper:]" "[:lower:]")
export device_id=${DEVICE_ID:-${DEVICE_UUID}} device_dir="${DEVICES_DIR}/${DEVICE_UUID}"
mkdir -p "${device_dir}"
----
+
Then, generate the device certificate and key using openssl:
+
[source,bash]
----
include::https://raw.githubusercontent.com/advancedtelematic/ota-community-edition/master/scripts/start.sh[tags="genclientkeys"]
----
. Add the internal root CA certificate of the device gateway the device will connect to. To get the device gateway's certificate, use openssl:
+
----
export device_gateway=your-gateway-url # for OTA Connect, looks something like
    # a3378fca-4e4c-4a5d-b1c2-d5c5ec35b3c2.tcpgw.prod01.advancedtelematic.com
openssl s_client -connect ${device_gateway}:8000 -servername $device_gateway -showcerts | \
  sed -n '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > ${device_dir}/root.crt
----
+
Once you have the required components in place, you can link:enable-implicit-provisioning.html[provision with device credentials].
// end::install-root-ca[]
