= Use Case A
:page-layout: page
:page-categories: [lib-howto]
:page-date: 2018-11-26 13:56:56
:page-order: 99
:icons: font

////
The example/use case topics describe how to accomplish common use cases. They are larger that "how to" (perform a task) topics becasue they follow an entire example scenario from start to finish rather than just outlining the steps in a single isolated task.

The title of the topic should be in the imperative voice, for example:

    Display the Louvre Museum Using Tiles

Do not use gerunds, for example:

    Displaying the Louvre Museum Using Tiles

The introductory paragraph should describe a hypothetical but realistic scenario. For example:

    You want to get the venue level so that you can display venue-specific data on end users' devices .

Followed by an example code and commands Be sure to point out important parameters and explain why they are set as they are in the example. Use the example to teach important concepts as well as provide specifics on how to accomplish the hypothetical scenario.

For inspiration on "Use Case" topics, see this example: 
https://developer.here.com/documentation/venue-maps/topics/usecases-paris-louvre.html
////