= Why Use libaktualizr
:page-layout: page
:page-categories: [using-libaktualizr]
:page-date: 2018-11-28 14:06:25
:page-order: 1
:icons: font

////
This topic is supposed to outline the main use cases the product aims to address. The body of the guide must show how to use the product to implement these use cases.

For libaktualizr We already have this topic: https://docs.atsgarage.com/client-config/advanced-update-control-with-libaktualizr.html
The following text was taken from the linked topic and is a proposal for the introcdution to the integration guide.

Feel free to adapt it or leave as-is. 
////

The OTA Connect client (aktualizr) is designed to be run as a standalone component on an embedded system and can manage the entire software update process. However, you might have requirements that got beyond what the standalone client can provide.

For example, some in-vehicle interfaces are proprietary and under NDA, so their implementation must be kept separate from aktualizr. You might want to integrate the OTA update functionality yourself and minimize the involvement of external consultants.

For this purpose, you can also use libaktualizr to make your own OTA update client. Typical scenarios for making your own client could be:

* You want to integrate {product-name} functionality with a third-party HMI
* You want to integrate {product-name} with a third-party interface that installs software on secondary ECUs
* You want to constrain network traffic and software updates to specific vehicle states
* You want to provide motorists or service staff with progress indicators for specific software updates.

