= Rotate TUF keys
:page-layout: page
:page-categories: [quickstarts]
:page-date: 2017-05-23 16:31:35
:page-order: 6
:icons: font
:toc: macro

As part of the quickstart, your ATS Garage account creates and stores online the keys for signing the TUF repository of images.
Before you go into production, as a main security feature of the Uptane model used by ATS Garage,
you must rotate these online keys with offline keys that you manage yourself.

toc::[]


== Install the `garage-sign` tool

On a debian machine, download the `garage-deploy` package and install it:

----
wget https://github.com/advancedtelematic/aktualizr/releases/download/offline-signing-0.2.0-82/garage_deploy-amd64.deb
sudo dpkg -i garage_deploy-amd64.deb 
----

This package contains both the `garage-deploy` and `garage-sign` tools.

== Rotate the TUF `root` and `targets` keys

First, create a TUF repo directory structure with a name such as `mytufrepo`:

----
garage-sign init --repo mytufrepo --credentials /path/to/credentials.zip 
----

This command will create in your current working directory a `./tuf/mytufrepo/` directory tree.
You must keep this directory secure on an encrypted filesystem.

Second, generate new keys for the TUF `root` and `targets` roles:

----
garage-sign gen-keys --repo mytufrepo --name myroot --type rsa
garage-sign gen-keys --repo mytufrepo --name mytargets --type rsa
----

These keys must be kept offline on secure hardware.

Finally, rotate the online keys with your new offline keys:

----
garage-sign rotate --repo mytufrepo --old-root-alias origroot --new-root myroot --new-targets mytargets
----

This command will:

- remove the original root key from ATS Garage
- generate a new `root.json` with the new `root` and `targets` keys
- sign the new `root.json` with both the old and new `root` keys
- upload the new signed `root.json` to ATS Garage

You have successfully taken the TUF keys offline.
Note that you will no longer be able to upload packages through the ATS Garage application.

== Push new images with `bitbake`

Export the new offline `targets` into a new credentials file that you can use with `bitbake`:

----
garage-sign export-credentials --repo mytufrepo --target-key-name mytargets --to offline-credentials.zip
----

Update your `conf/local.conf` to use the new `offline-credentials.zip` file and run `bitbake` as before.

As part of the `bitbake` process, the images are signed with your offline TUF keys.
The signed `targets.json` is then uploaded to your ATS Garage account.
